package com.myspace.airtelcloudplanning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class orderDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public orderDetails() {
    }




}